name: Allocate funds

on:
  workflow_dispatch:
    inputs:
      round:
        description: 'which round'
        required: true
        type: choice
        options:
        - 1
        - 2
        - 3
      budget:
        description: 'How much is available'
        required: true

jobs:
  funding-sdg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests pyyaml numpy

      - name: Run SDG allocate funding
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/allocate_funds.py ${{ inputs.round }} --budget ${{ inputs.budget }}
